<?php
                    return [
                        'key' => 'b2b',
                        'priority' => 200,
                        'name' => 'B2B',
                        'description' => 'Project generated by user using generator',
                        'namespace' => '\Eagle\B2B',
                        'group' => 'Generator',
                        'version' => 0.1,
                    ];