<?php
/**
 * @var $file \Eagle\Crud\Models\Form
 */
?>

<table class="table table-striped table-bordered table-hover">
    <tr>
        <th>Name</th>
        <th>Create</th>
    </tr>
    <?php

    foreach ($crud_files as $file):

    ?>
        <tr>
            <td><?php echo $file->getName(); ?></td>
            <td>
            <?php $this->partial($this->config->template->admin->partials->edit,
                array(
                    'url' => '/crud/index/create',
                    'id' => $file->getName(),
                    'name' => 'Create ' . $file->getName()
                )
            ); ?>
            </td>

        </tr>
    <?php endforeach; ?>

</table>
