<?php
/**
 * @var $file \Eagle\Crud\Models\Form
 */
?>

<table class="table table-striped table-bordered table-hover">
    <tr>
        <th>Name</th>
        <th>Create</th>
    </tr>

        <tr>
            <td><?php echo $crud_project->getName(); ?></td>
            <td>
            <?php $this->partial($this->config->template->admin->partials->edit,
                array(
                    'url' => '/crud/index/create',
                    'id' => $crud_project->getName(),
                    'name' => 'Create ' . $crud_project->getName()
                )
            ); ?>
            </td>

        </tr>


</table>
