<table class="table table-striped table-bordered table-hover">
    <tr>
        <th>Name</th>
        <th>Create</th>
    </tr>
    <?php

    foreach ($crud_files as $file):

        ?>
        <tr>
            <td><?php echo $file->name; ?></td>
            <td>
            <?php $this->partial($this->config->template->admin->partials->edit,
                array(
                    'url' => '/crud/index/create',
                    'id' => $file->name,
                    'name' => 'Create ' . $file->name,
                )
            ); ?>
            </td>

        </tr>
    <?php endforeach; ?>

</table>
