<?php
/**
 * @var \Eagle\Core\Forms\Install $this
 */

echo $this->renderForm();

?>

    <table class="table table-striped table-bordered table-hover">
        <tr>
            <th class="center">Installed</th>
            <th>Name</th>
            <th>Version</th>
            <th>Priority</th>
            <th>Description</th>
            <th>Configure</th>
            <th>Permissions</th>
        </tr>
        <?php

        $modules = $this->getModules();

        foreach ($this->getElements() as $element_key => $element):

            if ($element instanceof \Phalcon\Forms\Element\Submit):
                continue;
            endif;
            ?>
            <tr>
                <td class="center"><?php echo $element->render(); ?></td>
                <td><?php echo $element->getLabel(); ?></td>
                <td><?php echo $modules[$element_key]['version']; ?></td>
                <td><?php echo $modules[$element_key]['priority']; ?></td>
                <td><?php echo $modules[$element_key]['description']; ?></td>
                <td>-</td>
                <td>-</td>
            </tr>
        <?php endforeach; ?>

    </table>

<?php


echo $this->renderEndForm();
