<?php
/**
 * @var \Eagle\Themes\Forms\Themes $this
 */


echo $this->renderForm();
?>
<table class="table table-striped table-bordered table-hover">
    <tr>
        <th>&nbsp;</th>
        <th>Name</th>
        <th>Version</th>
        <th>------</th>
    </tr>
    <?php

    foreach ($this->_themes as $element_name => $data):?>
        <tr>
            <td>&nbsp;</td>
            <td><?php echo $data['name']; ?></td>
            <td><?php echo $data['version']; ?></td>
            <td><?php echo $this->render($element_name); ?></td>
        </tr>
    <?php endforeach; ?>


</table>
<?php echo $this->renderEndForm();