<table class="table table-striped table-bordered table-hover">
    <tr>
        <th>&nbsp;</th>
        <th>Name</th>
        <th>Version</th>
        <th>------</th>
    </tr>
    <?php
    foreach ($themes as $data):?>
        <tr>
            <td>&nbsp;</td>
            <td><?php echo $data['name']; ?></td>
            <td><?php echo $data['version']; ?></td>
            <td><?php
                if ($this->config->template->admin->name == $data['name']):
                    echo "Admin";
                elseif ($this->config->template->front->name == $data['name']):
                    echo "Front";
                else:
                    echo "innactive";
                endif;?></td>
        </tr>
    <?php endforeach; ?>


</table>